version: "3.9"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/home/vscode/devcontainer
    environment:
      PYTHONPATH: /home/vscode/devcontainer
    command: sleep infinity
